"""add bio to orm_users

Revision ID: 52806ef93ca3
Revises: e5a9a163a89b
Create Date: 2026-09-23 14:58:41.198945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52806ef93ca3'
down_revision: Union[str, Sequence[str], None] = 'e5a9a163a89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orm_users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orm_users', 'bio')
    # ### end Alembic commands ###
